trigger:
  branches:
    include:
      - main  # Trigger pipeline on commits to the main branch

pool:
  name: 'Default'

variables:
  - group: dev_vars

stages:
  # Stage 1: Initialization (init, validate, lint)
  - stage: Initialization
    jobs:
      - job: TerraformInit
        steps:
          - task: TerraformInstaller@0  # Install Terraform
            inputs:
              terraformVersion: $(terraformVersion)

          # Initialize Terraform
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              backendServiceArm: $(azureServiceConnection)
              backendAzureRmResourceGroupName: $(backendResourceGroup)
              backendAzureRmStorageAccountName: $(backendStorageAccount)
              backendAzureRmContainerName: $(backendContainer)
              backendAzureRmKey: $(backendKey)
              command: 'init'  # Initialize Terraform
              workingDirectory: $(workingdir)  # Set the working directory
            displayName: 'INIT task'

          # Validate Terraform configuration
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'validate'  # Validate Terraform configuration
              workingDirectory: '$(workingdir)'
            displayName: 'VALIDATE task'

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'plan'  # Run terraform plan
              environmentServiceNameAzureRM: $(azureServiceConnection)  # Azure service connection for authentication
              workingDirectory: $(workingdir)  # Set the working directory
            displayName: 'PLAN task'
            
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'apply'  # Run terraform apply
              backendServiceArm: $(azureServiceConnection)
              commandOptions: '--auto-approve'
              environmentServiceNameAzureRM: $(azureServiceConnection)  # Azure service connection for authentication
              workingDirectory: $(workingdir)  # Set the working directory
            displayName: 'APPLY task'
            
