trigger:
  branches:
    include:
      - main  # Trigger pipeline on commits to the main branch

pool:
  name: 'Default'

variables:
  terraformVersion: '1.5.5'  # Specify the Terraform version
  azureServiceConnection: 'azurerm'  # Azure service connection name
  backendResourceGroup: 'myTFResourceGroup' # Remote backend Resource Group
  backendStorageAccount: 'fedeflowerstorage'  # Remote backend storage account
  backendContainer: 'tfstate'  # Remote backend storage container
  backendKey: 'terraform.tfstate'  # State file name in remote backend
  workingdir: 'Basic_pipeline/terraform'

stages:
  # Stage 1: Initialization (init, validate, lint)
  - stage: Initialization
    jobs:
      - job: TerraformInit
        steps:
          - task: TerraformInstaller@0  # Install Terraform
            inputs:
              terraformVersion: $(terraformVersion)

          # Initialize Terraform
          - task: TerraformTaskV4@4
            displayName: 'INIT task'
            inputs:
              provider: 'azurerm'
              backendServiceArm: $(azureServiceConnection)
              backendAzureRmResourceGroupName: $(backendResourceGroup)
              backendAzureRmStorageAccountName: $(backendStorageAccount)
              backendAzureRmContainerName: $(backendContainer)
              backendAzureRmKey: $(backendKey)
              command: 'init'  # Initialize Terraform
              workingDirectory: $(workingdir)  # Set the working directory

          # Validate Terraform configuration
          - task: TerraformTaskV4@4
            displayName: 'VALIDATE task'
            inputs:
              provider: 'azurerm'
              command: 'validate'  # Validate Terraform configuration
              workingDirectory: '$(workingdir)'

          - task: TerraformTaskV4@4
            displayName: 'PLAN task'
            inputs:
              provider: 'azurerm'
              command: 'plan'  # Run terraform plan
              environmentServiceNameAzureRM: $(azureServiceConnection)  # Azure service connection for authentication
              workingDirectory: $(workingdir)  # Set the working directory
            
          - task: TerraformTaskV4@4
            displayName: 'APPLY task'
            inputs:
              provider: 'azurerm'
              command: 'apply'  # Run terraform apply
              commandOptions: '--auto-approve'
              environmentServiceNameAzureRM: $(azureServiceConnection)  # Azure service connection for authentication
              workingDirectory: $(workingdir)  # Set the working directory