$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

settings:
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

# All inputs come from Azure Storage (no local files)
inputs:
  # Latest data: folder or MLTable in the raw datastore
  latest_data:
    type: uri_folder
    # Example: points at a container path that contains an MLTable file and partitions
    path: azureml://datastores/raw/paths/landing
  # Baseline: versioned immutable data asset (registered once)
  baseline:
    type: uri_file
    path: azureml:iris-baseline:1
  min_acc:
    type: string
    default: 0.90
  drift_threshold:
    type: string
    default: 0.15

outputs:
  model_out: { type: uri_folder }

jobs:
  drift:
    type: command
    component: ../components/drift_check/component.yml
    inputs:
      baseline: ${{parent.inputs.baseline}}
      latest_data: ${{parent.inputs.latest_data}}
      threshold: ${{parent.inputs.drift_threshold}}
    outputs:
      drift_signal: {}

  prep:
    type: command
    component: ../components/prep/component.yml
    inputs:
      latest_folder: ${{parent.inputs.latest_data}}
      drift_signal: ${{parent.jobs.drift.outputs.drift_signal}}
    outputs:
      output_path: {}

  train:
    type: command
    component: ../components/train/component.yml
    inputs:
      train_folder: ${{parent.jobs.prep.outputs.output_path}}
    outputs:
      model_dir: ${{parent.outputs.model_out}}

  evaluate:
    type: command
    component: ../components/evaluate/component.yml
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
      min_acc: ${{parent.inputs.min_acc}}

  register_deploy:
    type: command
    environment: ../environments/sklearn-env.yml
    code: ../deployment/src
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
    command: >-
      python - <<'PY'
      import os
      from azure.identity import DefaultAzureCredential
      from azure.ai.ml import MLClient
      from azure.ai.ml.entities import Model

      sub = os.environ["AZURE_SUBSCRIPTION_ID"]
      rg  = os.environ["AZUREML_RESOURCE_GROUP"]
      ws  = os.environ["AZUREML_WORKSPACE_NAME"]

      mlc = MLClient(DefaultAzureCredential(), sub, rg, ws)
      mpath = "${{inputs.model_dir}}"
      model = Model(path=mpath, name="sklearn-iris", type="mlflow_model")
      model = mlc.models.create_or_update(model)
      print("Model registered:", model.name, model.version)
      PY
