$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: sklearn-iris-endpoint
environment: ../environments/sklearn-env.yml
model: azureml:sklearn-iris@latest
code_configuration:
  code: .
  scoring_script: score.py
instance_type: Standard_DS2_v2
instance_count: 1