trigger:
  branches:
    include: 
    - main

pr:
  branches:
    include: 
    - main

pool:
  name: 'Default'

variables:
  - group: dev_vars

stages:
- stage: CI
  displayName: Infra CI (validate & plan)
  jobs:
  - job: TerraformCI
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: $(terraformVersion)

    - task: TerraformTaskV4@4
      displayName: INIT
      inputs:
        provider: azurerm
        backendServiceArm: $(azureServiceConnection)
        backendAzureRmResourceGroupName: $(backendResourceGroup)
        backendAzureRmStorageAccountName: $(backendStorageAccount)
        backendAzureRmContainerName: $(backendContainer)
        backendAzureRmKey: $(backendKey)
        command: init
        workingDirectory: $(workingdir)

#unlock state if needed
    # - script: |
    #     set -e
    #     terraform init -input=false
    #     terraform force-unlock -force "5db31b9e-e804-693a-31bf-0f42ea8e3723" || true
    #   displayName: Terraform force-unlock (always)
    #   workingDirectory: $(workingdir)
          
    - task: TerraformTaskV4@4
      displayName: PLAN
      inputs:
        provider: azurerm
        command: plan
        environmentServiceNameAzureRM: $(azureServiceConnection)
        commandOptions: -out=tfplan -var-file="envs/$(environment)/terraform.tfvars"
        workingDirectory: $(workingdir)

    # Export human-readable JSON (only if tfplan exists)
    - task: PowerShell@2
      displayName: Export plan as JSON (optional)
      inputs:
        targetType: inline
        workingDirectory: $(workingdir)
        script: |
          if (Test-Path "tfplan") {
            New-Item -ItemType Directory -Force -Path "$env:BUILD_ARTIFACTSTAGINGDIRECTORY" | Out-Null
            terraform show -json tfplan > "$env:BUILD_ARTIFACTSTAGINGDIRECTORY\tfplan.json"
            Write-Host "Wrote $env:BUILD_ARTIFACTSTAGINGDIRECTORY\tfplan.json"
          } else {
            Write-Host "No tfplan found; skipping JSON export."
          }

    # Collect the binary tfplan (only if it exists)
    - task: PowerShell@2
      displayName: Collect plan artifact
      inputs:
        targetType: inline
        script: |
          New-Item -ItemType Directory -Force -Path "$(Build.ArtifactStagingDirectory)" | Out-Null
          if (Test-Path "$(workingdir)\tfplan") {
            Copy-Item -Path "$(workingdir)\tfplan" -Destination "$(Build.ArtifactStagingDirectory)\tfplan" -Force
            Write-Host "Copied tfplan to artifact staging."
          } else {
            Write-Host "No tfplan found; skipping copy."
          }

    # Publish (it’s fine if the folder is empty)
    - publish: $(Build.ArtifactStagingDirectory)
      displayName: Publish plan artifact
      artifact: tfplan
      condition: succeeded()

