trigger:
  branches:
    include: 
    - main

pr:
  branches:
    include: 
    - main

pool:
  name: 'Default'

variables:
  - group: dev_vars

stages:
- stage: CI
  displayName: Infra CI (validate & plan)
  jobs:
  - job: TerraformCI
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: $(terraformVersion)

    - task: TerraformTaskV4@4
      displayName: INIT
      inputs:
        provider: azurerm
        backendServiceArm: $(azureServiceConnection)
        backendAzureRmResourceGroupName: $(backendResourceGroup)
        backendAzureRmStorageAccountName: $(backendStorageAccount)
        backendAzureRmContainerName: $(backendContainer)
        backendAzureRmKey: $(backendKey)
        command: init
        workingDirectory: $(workingdir)

#unlock if needed
    # - script: |
    #     set -e
    #     terraform init -input=false
    #     terraform force-unlock -force "5db31b9e-e804-693a-31bf-0f42ea8e3723" || true
    #   displayName: Terraform force-unlock (always)
    #   workingDirectory: $(workingdir)
          
    - task: TerraformTaskV4@4
      displayName: PLAN
      inputs:
        provider: azurerm
        command: plan
        environmentServiceNameAzureRM: $(azureServiceConnection)
        commandOptions: -out=tfplan -var-file="envs/$(environment)/terraform.tfvars"
        workingDirectory: $(workingdir)

    - script: |
        mkdir -p $(Build.ArtifactStagingDirectory)
        cp $(workingdir)/tfplan $(Build.ArtifactStagingDirectory)/
      displayName: Collect plan artifact

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: tfplan
      displayName: Publish plan artifact

