trigger:
  branches: { include: [ main ] }
  paths: { include: [ ml/** ] }

pool: { vmImage: ubuntu-latest }

steps:
  - task: UsePythonVersion@0
    inputs: { versionSpec: '3.10' }
  - script: |
      python -m pip install -U pip
      pip install -r requirements.txt
      flake8 ml
      pytest -q
    displayName: "Lint & test"
  - publish: ml
    artifact: ml_code